
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Describes objects present in a room based on uploaded photos.
 *
 * - describeRoomObjects - A function that takes room photos and returns a list of object names.
 * - DescribeRoomObjectsInput - The input type for the describeRoomObjects function.
 * - DescribeRoomObjectsOutput - The return type for the describeRoomObjects function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DescribeRoomObjectsInputSchema = z.object({
  photoDataUris: z
    .array(z.string())
    .describe(
      'An array of photo URLs of a room. These URLs should be publicly accessible or signed URLs that the AI model can retrieve.'
    ),
});
export type DescribeRoomObjectsInput = z.infer<typeof DescribeRoomObjectsInputSchema>;

const DescribeRoomObjectsOutputSchema = z.object({
  objectNames: z
    .array(z.string())
    .describe('A list of names of all distinct objects identified in the room photos.'),
});
export type DescribeRoomObjectsOutput = z.infer<typeof DescribeRoomObjectsOutputSchema>;

export async function describeRoomObjects(
  input: DescribeRoomObjectsInput
): Promise<DescribeRoomObjectsOutput> {
  return describeRoomObjectsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'describeRoomObjectsPrompt',
  input: {schema: DescribeRoomObjectsInputSchema},
  output: {schema: DescribeRoomObjectsOutputSchema},
  prompt: `You are an expert visual inspector AI specializing in meticulously identifying and listing every single object visible in images of rooms.
Your task is to analyze the provided images of a room with extreme attention to detail.
You must identify and list the name of *every single distinct item* visible in the photos. This includes small items, decorative objects, items in the background, items partially obscured, etc. Be exhaustive, highly accurate, and comprehensive.
Your output must be a list of object names only. Do not provide descriptions, counts, or any other information beyond the names of the identified items.

{{#each photoDataUris}}
Photo {{@index}}:
{{media url=this}}
{{/each}}`,
});

const describeRoomObjectsFlow = ai.defineFlow(
  {name: 'describeRoomObjectsFlow', inputSchema: DescribeRoomObjectsInputSchema, outputSchema: DescribeRoomObjectsOutputSchema},
  async input => {
    const {output} = await prompt(input);
    if (!output || !output.objectNames) {
      // Handle cases where output might be null or missing objectNames, though schema should enforce
      return { objectNames: [] };
    }
    return output;
  }
);
